package com.example.nteambe.domain.spot.enums;

public enum StatusType {
    PLEASANT, GOOD_FOR_TRAINING, GOOD_FOR_FILMING, CROWDED, WET_FLOOR,
    DARK_AT_NIGHT, GUARD_ENFORCED, FILMING_RESTRICTED, BEWARE_COMPLAINTS,
    DAMAGED_STRUCTURE, UNDER_CONSTRUCTION, ACCESS_CONTROLLED, FACILITY_CHANGED,
    REOPENED, SEASON_LIMITED
}